#!/usr/bin/env python3
"""gen_dd_expected.py -- expectations for the double-double library.

Writes tests/dd_expected.h from mpmath at 60 digits:

  * function cases: for each (function, arguments) the correctly rounded
    double-double is emitted as two hex floats (exact, so the C test can compare
    exactly) plus the value as a 33-significant-digit decimal string, which is
    what the printing test checks against;
  * string cases: decimal strings with more digits than a double can hold, with
    the exact double-double they denote.

Run from the project root:

    python3 tools/gen_dd_expected.py
"""
import os
import random
import struct
import sys

from mpmath import mp, mpf

mp.dps = 60
HERE = os.path.dirname(os.path.abspath(__file__))
TOP = os.path.dirname(HERE)
OUT = os.path.join(TOP, 'tests', 'dd_expected.h')

random.seed(20240926)


def split_dd(x):
    """the correctly rounded (hi, lo) representation of an mpf"""
    hi = float(x)
    lo = float(x - mpf(hi))
    # renormalise once: float() rounds to nearest, so hi + lo may need a tweak
    s = hi + lo
    if s != hi:
        e = (hi - s) + lo
        hi, lo = s, e
    return hi, lo


def hx(v):
    return float.hex(v) if v == v and abs(v) != float('inf') else (
        'nan' if v != v else ('inf' if v > 0 else '-inf'))


def dec33(x):
    s = mp.nstr(x, 33, strip_zeros=False)
    return s


CASES = []


def add(fn, args, value):
    hi, lo = split_dd(value)
    CASES.append((fn, [repr(float(a)) for a in args], dec33(value), hx(hi), hx(lo)))


def rnd(a, b):
    """An mpf holding EXACTLY the double the C side will feed in.

    The distinction matters: mpf('0.1') is the decimal 0.1, while the double
    0.1 is a different number (by ~5.5e-18).  The expectations must be computed
    from what plua_dd_from_double(strtod("0.1")) holds, i.e. the double, or
    every case would show a spurious ~1e-17 relative error.
    """
    return mpf(float(random.uniform(a, b)))


def build():
    from mpmath import (sin, cos, tan, asin, acos, atan, atan2, exp, log, log10,
                        sqrt, power, hypot)

    for _ in range(60):
        x = rnd(-8, 8)
        add('sin', [x], sin(x))
        add('cos', [x], cos(x))
        add('tan', [x], tan(x))
        add('atan', [mpf(float(x * 6))], atan(mpf(float(x * 6))))
    for _ in range(10):                       # argument reduction at scale
        x = rnd(1e4, 1e6)
        add('sin', [x], sin(x))
        add('cos', [x], cos(x))
    for _ in range(40):
        x = rnd(-0.999, 0.999)
        add('asin', [x], asin(x))
        add('acos', [x], acos(x))
    for _ in range(30):
        y, x = rnd(-10, 10), rnd(-10, 10)
        add('atan2', [y, x], atan2(y, x))
    for _ in range(60):
        x = rnd(-20, 20)
        add('exp', [x], exp(x))
    for _ in range(6):                        # near the overflow/underflow ends
        x = rnd(80, 700)
        add('exp', [x], exp(x))
        y = rnd(-700, -80)
        add('exp', [y], exp(y))
    for _ in range(60):
        x = rnd(1e-8, 1e8)
        add('log', [x], log(x))
        add('log10', [x], log10(x))
    for _ in range(12):                       # log near 1
        x = mpf(float(1 + rnd(-1e-6, 1e-6)))
        add('log', [x], log(x))
        add('log10', [x], log10(x))
    for _ in range(30):
        x = rnd(0, 1e6)
        add('sqrt', [x], sqrt(x))
    for _ in range(30):
        b, e = rnd(0.1, 10), rnd(-5, 5)
        add('pow', [b, e], power(b, e))
    for _ in range(10):
        b, e = rnd(0.5, 4), mpf(random.randint(-6, 6))
        add('pow', [b, e], power(b, e))
    for _ in range(20):
        a, b = rnd(-1e3, 1e3), rnd(-1e3, 1e3)
        add('hypot', [a, b], hypot(a, b))
    add('pi', [mpf(0)], mp.pi)
    add('e', [mpf(0)], mp.e)
    add('ln2', [mpf(0)], mp.log(2))
    add('ln10', [mpf(0)], mp.log(10))


STR_CASES = []
STRINGS = [
    '0.1', '3.14159265358979323846264338327950288',
    '2.71828182845904523536028747135266250',
    '1.41421356237309504880168872420969808',
    '0.000123456789012345678901234567890123',
    '-9.87654321098765432109876543210987e-7',
    '6.02214076e23', '1.602176634e-19',
    '123456789012345678901234567890.12345',
    '0.999999999999999999999999999999999',
]


def build_strings():
    for s in STRINGS:
        v = mpf(s)
        hi, lo = split_dd(v)
        STR_CASES.append((s, dec33(v), hx(hi), hx(lo)))


def main():
    build()
    build_strings()
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('/* GENERATED by tools/gen_dd_expected.py from mpmath at 60 digits '
                 '-- do not edit. */\n')
        fh.write('#ifndef DD_EXPECTED_H\n#define DD_EXPECTED_H\n\n')
        fh.write('typedef struct {\n'
                 '\tconst char *fn;\n\tconst char *a1;\n\tconst char *a2;\n'
                 '\tconst char *want;\n\tconst char *want_hi;\n'
                 '\tconst char *want_lo;\n} dd_case;\n\n')
        fh.write('static const dd_case dd_cases[] = {\n')
        for fn, args, want, hi, lo in CASES:
            a2 = args[1] if len(args) > 1 else '0'
            fh.write('\t{"%s", "%s", "%s", "%s", "%s", "%s"},\n'
                     % (fn, args[0], a2, want, hi, lo))
        fh.write('};\n\n')
        fh.write('typedef struct {\n\tconst char *text;\n\tconst char *want;\n'
                 '\tconst char *want_hi;\n\tconst char *want_lo;\n} dd_strcase;\n\n')
        fh.write('static const dd_strcase dd_strcases[] = {\n')
        for text, want, hi, lo in STR_CASES:
            fh.write('\t{"%s", "%s", "%s", "%s"},\n' % (text, want, hi, lo))
        fh.write('};\n\n#endif\n')
    print('%s: %d function cases, %d string cases'
          % (OUT, len(CASES), len(STR_CASES)))


if __name__ == '__main__':
    sys.exit(main())
