#!/usr/bin/env python3
"""make_font_cascadia.py -- rasterize Cascadia Code Light, primeLua's monospace
family, at the three sizes it draws with.

primeLua ships exactly TWO families:

    prop -- Montserrat, proportional advances        (make_font_montserrat.py)
    mono -- Cascadia Code Light, fixed-width cell    (this script)

Why this script exists instead of another extraction: primetcc's committed
glyph table holds a DIFFERENT monospace face, and primeLua wants Cascadia --
every glyph including ":" has the same advance, so the digits of a clock never
shift.  So the face is rasterized here:

    primetcc/rt/tools/fontgen2.py  (PIL, 4-bit alpha, same conventions)
        + fonts/Montserrat-w450.ttf, Montserrat-Regular.ttf,
          CascadiaCode-Light.ttf           ->  a full 8-face table in a temp file
        -> the mono 16/24/32 px rows are lifted out of THAT file and renamed.

primetcc is not modified: fontgen2.py is run read-only and its output is thrown
away after the extraction.  Run it after a primetcc font update:

    python3 tools/make_font_cascadia.py     # writes port/plua_font_cascadia_data.c

The output is committed, so a normal build needs neither PIL nor the TTF.

The file also carries hp_font_mono_data(), the accessor primetcc's font engine
(rt/hp_fonts.c) calls for its monospace family: with this file linked, the
engine's hp_font_mono() IS Cascadia, so font.mono() and font.cascadia() hand
back the same face.
"""
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
TOP = os.path.dirname(HERE)
PRIMETCC = os.environ.get(
    'PRIMETCC', os.path.join(os.path.dirname(TOP), 'primetcc'))
GEN = os.path.join(PRIMETCC, 'rt', 'tools', 'fontgen2.py')
FONTS = os.path.join(PRIMETCC, 'rt', 'tools', 'fonts')
OUT = os.path.join(TOP, 'port', 'plua_font_cascadia_data.c')
# 16 / 24 / 32 px, the same three sizes the Montserrat faces ship.
SIZES = (16, 24, 32)

# fontgen2.py's argv: prop-12 (Montserrat Medium/w450), prop-16+ (Regular),
# mono (Cascadia Code Light) -- the files primetcc's own README documents
ARGV = ['Montserrat-w450.ttf', 'Montserrat-Regular.ttf', 'CascadiaCode-Light.ttf']


def array_text(src, name):
    """The whole `static const <type> name[...] = { ... };` declaration."""
    m = re.search(r'^static const [a-z_ ]*%s\[[^\]]*\] = \{.*?^\};'
                  % re.escape(name), src, re.S | re.M)
    if not m:
        raise SystemExit('array %s not found in the generated table' % name)
    return m.group(0)


def table_entry(src, table, want_size):
    m = re.search(r'static const hp_font %s\[4\] = \{(.*?)\n\};' % table,
                  src, re.S)
    if not m:
        raise SystemExit('table %s not found' % table)
    for row in re.findall(r'\{([^{}]*)\}', m.group(1)):
        fields = [f.strip() for f in row.split(',')]
        if len(fields) >= 7 and fields[0] == str(want_size):
            return fields
    raise SystemExit('no %d px row in %s' % (want_size, table))


def generate():
    """fontgen2.py's output for all eight faces, in memory."""
    for name in ARGV:
        p = os.path.join(FONTS, name)
        if not os.path.exists(p):
            raise SystemExit('missing TTF: %s' % p)
    r = subprocess.run([sys.executable, GEN] + [os.path.join(FONTS, a)
                                               for a in ARGV],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit('fontgen2.py failed:\n' + r.stderr[-2000:])
    return r.stdout


def main():
    src = generate()

    chunks, descs, sizes_done = [], [], []
    for SIZE in SIZES:
        fields = table_entry(src, 'hp_font_mono_table', SIZE)
        gtxt = array_text(src, 'hp_glyphs_mono_%d' % SIZE) \
            .replace('hp_glyphs_mono_%d' % SIZE,
                     'plua_glyphs_cascadia_%d' % SIZE, 1)
        btxt = array_text(src, 'hp_bits_mono_%d' % SIZE) \
            .replace('hp_bits_mono_%d' % SIZE,
                     'plua_bits_cascadia_%d' % SIZE, 1)
        chunks += [gtxt, btxt]
        descs.append(
            'const hp_font plua_font_cascadia%d = {%s, %s, %s, %s, %s,\n'
            '                               plua_glyphs_cascadia_%d,'
            ' plua_bits_cascadia_%d};'
            % (SIZE, fields[0], fields[1], fields[2], fields[3], fields[4],
               SIZE, SIZE))
        sizes_done.append((SIZE, fields[4]))

    header = '''/*
 * plua_font_cascadia_data.c -- Cascadia Code Light at %s px.
 *
 * GENERATED by tools/make_font_cascadia.py -- do not edit by hand.  The glyph
 * descriptors and the packed 4-bit-per-pixel bitmaps come from primetcc's
 * rt/tools/fontgen2.py run over rt/tools/fonts/CascadiaCode-Light.ttf (SIL Open
 * Font License 1.1); each hp_font row is re-derived from that run's
 * hp_font_mono_table.  primetcc is neither modified nor linked.
 *
 * This is the image's MONOSPACE family: the cell is fixed, so every glyph --
 * ":" included -- advances by the same amount and the digits of a clock never
 * shift.  It is what hp_font_mono() (primetcc's engine) and port/plua_hp.c's
 * font.mono()/font.cascadia() hand back; the proportional family (Montserrat)
 * lives in port/plua_font_montserrat_data.c.
 */
#include "hp_fonts.h"          /* the hp_glyph / hp_font layouts */

''' % (', '.join(str(sz) for sz, _ in sizes_done))

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(header)
        fh.write('\n'.join(chunks))
        # the descriptors MUST come before the table that points at them
        fh.write('\n\n/* the faces, one per size */\n')
        fh.write('\n'.join(descs))
        fh.write('\n\n/* the faces the port exposes, ordered by size */\n')
        fh.write('const hp_font *plua_cascadia_faces[] = {%s};\n'
                 % ', '.join('&plua_font_cascadia%d' % sz
                             for sz, _ in sizes_done))
        fh.write('const int plua_cascadia_count = %d;\n' % len(sizes_done))
        fh.write("""
/* Nearest-size pick, the same rule primetcc's own engine uses (hp_fonts.c
 * pick()): the caller asks for a size and gets the closest face that exists.
 * font.mono(20) therefore draws 24 px and font.mono(14) draws 16 px. */
const hp_font *plua_font_cascadia(int size)
{
	int i, best = 0, bd = 1 << 30;
	for (i = 0; i < plua_cascadia_count; i++) {
		int d = plua_cascadia_faces[i]->size - size;
		if (d < 0)
			d = -d;
		if (d < bd) {
			bd = d;
			best = i;
		}
	}
	return plua_cascadia_faces[best];
}

/*
 * primetcc's font engine (rt/hp_fonts.c, linked into the image unchanged) asks
 * for its monospace face by index 0..3 through this function and expects a
 * valid font for EVERY index.  Three sizes ship, so index 3 resolves to the
 * largest -- the engine's nearest-size search can only miss by one step.
 */
const hp_font *hp_font_mono_data(int i)
{
	if (i < 0 || i >= plua_cascadia_count)
		i = plua_cascadia_count - 1;
	return plua_cascadia_faces[i];
}
""")

    print('%s: %d B written (Cascadia Code Light %s px, cells %s)'
          % (OUT, os.path.getsize(OUT),
             '/'.join(str(sz) for sz, _ in sizes_done),
             '/'.join(str(c) for _, c in sizes_done)))


if __name__ == '__main__':
    sys.exit(main())
