#!/usr/bin/env python3
"""make_font_montserrat.py -- lift Montserrat (proportional) out of primetcc's
generated font tables, at the three sizes primeLua draws with.

primeLua ships exactly TWO families:

    prop -- Montserrat, proportional advances        (this script)
    mono -- Cascadia Code Light, fixed-width cell    (make_font_cascadia.py)

Why extraction instead of linking primetcc's font data:
  * `rt/hp_fonts_data.c` holds EIGHT faces (4 sizes x proportional/monospace)
    in one translation unit, and its accessor `hp_font_prop_data(i)` indexes
    the array with a RUNTIME index, so the linker has to keep the whole ~70 KB
    of glyph data even if the port only ever draws one size.
  * primeLua wants three Montserrat sizes and nothing else: ~26 KB instead of
    ~70 KB in the image, and primetcc itself is not touched.

So this script copies the three `hp_glyph` tables and their three bitmap pools
verbatim (renamed), and re-derives the three `hp_font` descriptors from the
original table literals.  The monospace family is NOT taken from here: since
primetcc's committed mono table holds a different face, primeLua rasterizes
Cascadia Code Light itself -- see tools/make_font_cascadia.py.

Run it after a primetcc font update:

    python3 tools/make_font_montserrat.py   # writes port/plua_font_montserrat_data.c

The output is committed, so a normal build needs neither primetcc's
hp_fonts_data.c nor python: the file is self-contained.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOP = os.path.dirname(HERE)
PRIMETCC = os.environ.get(
    'PRIMETCC', os.path.join(os.path.dirname(TOP), 'primetcc'))
SRC = os.path.join(PRIMETCC, 'rt', 'hp_fonts_data.c')
OUT_NAME = 'plua_font_montserrat_data.c'
OUT = os.path.join(TOP, 'port', OUT_NAME)

# 16 / 24 / 32 px.  primetcc prerenders 12/16/24/32; 12 is dropped because the
# port never asks for a size below 16 (PLUA_FONT_SIZE) and every face costs
# ~5-9 KB.
SIZES = (16, 24, 32)
FACES = [('prop', sz) for sz in SIZES]


def array_text(src, name):
    """The whole `static const <type> name[...] = { ... };` declaration."""
    m = re.search(r'^static const [a-z_ ]*%s\[[^\]]*\] = \{.*?^\};' % re.escape(name),
                  src, re.S | re.M)
    if not m:
        raise SystemExit('array %s not found in %s' % (name, SRC))
    return m.group(0)


def table_entry(src, table, want_size):
    """The {size, line_h, ascent, first, last, glyphs, bits} row for a size."""
    m = re.search(r'static const hp_font %s\[4\] = \{(.*?)\n\};' % table,
                  src, re.S)
    if not m:
        raise SystemExit('table %s not found' % table)
    for row in re.findall(r'\{([^{}]*)\}', m.group(1)):
        fields = [f.strip() for f in row.split(',')]
        if len(fields) >= 7 and fields[0] == str(want_size):
            return fields
    raise SystemExit('no %d px row in %s' % (want_size, table))


def main():
    with open(SRC, encoding='utf-8') as fh:
        src = fh.read()

    chunks = []
    descs = []
    for face, size in FACES:
        glyphs = 'hp_glyphs_%s_%d' % (face, size)
        bits = 'hp_bits_%s_%d' % (face, size)
        fields = table_entry(src, 'hp_font_%s_table' % face, size)
        # hp_glyphs_prop_16 -> plua_glyphs_prop_16
        gtxt = array_text(src, glyphs).replace(glyphs, 'plua_' + glyphs[3:], 1)
        btxt = array_text(src, bits).replace(bits, 'plua_' + bits[3:], 1)
        chunks.append(gtxt)
        chunks.append(btxt)
        descs.append(
            'const hp_font plua_font_%s%d = {%s, %s, %s, %s, %s,\n'
            '                              plua_%s, plua_%s};'
            % (face, size, fields[0], fields[1], fields[2], fields[3],
               fields[4], glyphs[3:], bits[3:]))

    header = '''/*
 * plua_font_montserrat_data.c -- Montserrat (proportional) at %s px.
 *
 * GENERATED by tools/make_font_montserrat.py from primetcc's rt/hp_fonts_data.c
 * -- do not edit by hand.  The glyph descriptors and the packed 4-bit-per-pixel
 * bitmaps are copied verbatim (only renamed); the three hp_font rows are
 * re-derived from the original hp_font_prop_table.
 *
 * Montserrat is SIL Open Font License 1.1, rasterized offline by primetcc's
 * rt/tools/fontgen2.py.  primetcc itself is not modified or linked: this file
 * is self-contained.  The monospace family lives in
 * port/plua_font_cascadia_data.c (Cascadia Code Light, same three sizes).
 *
 * Cost in the image: 3 x (760 B glyphs + bitmap pool), ~26 KB -- against
 * ~70 KB for the full eight-face table, which is what linking hp_fonts_data.c
 * would pull in (its accessor indexes the table with a runtime index, so
 * --gc-sections cannot drop the faces nobody draws).
 */
#include "hp_fonts.h"          /* the hp_glyph / hp_font layouts */

''' % ('/'.join(str(sz) for _, sz in FACES))

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(header)
        fh.write('\n'.join(chunks))
        fh.write('\n\n/* the Montserrat faces, ordered by size */\n')
        fh.write('\n'.join(descs))
        fh.write("\n\n/* the faces the port exposes, ordered by size */\n")
        fh.write("const hp_font *plua_prop_faces[] = {%s};\n"
                 % ', '.join('&plua_font_prop%d' % sz for _, sz in FACES))
        fh.write("const int plua_prop_count = %d;\n" % len(FACES))
        fh.write("""
/*
 * primetcc's font engine (rt/hp_fonts.c, linked into the image unchanged) asks
 * for a face by index 0..3 through this function and expects a valid font for
 * EVERY index.  Only three sizes ship, so index 3 resolves to the largest: the
 * engine's own nearest-size search (hp_font_prop) walks the indices it is given
 * and can therefore never miss the requested size by more than one step.
 *
 * The monospace counterpart, hp_font_mono_data(), is in the Cascadia file --
 * that is the face primeLua uses for font.mono().
 */
const hp_font *hp_font_prop_data(int i)
{
	if (i < 0 || i >= plua_prop_count)
		i = plua_prop_count - 1;
	return plua_prop_faces[i];
}
""")

    print('%s: %d B written (Montserrat %s px)'
          % (OUT, os.path.getsize(OUT),
             '/'.join(str(sz) for _, sz in FACES)))


if __name__ == "__main__":
    sys.exit(main())
