#!/usr/bin/env python3
"""make_font16.py -- extract two font faces out of primetcc's generated tables.

Why extraction instead of linking primetcc's font engine:
  * `rt/hp_fonts_data.c` holds EIGHT faces (4 sizes x proportional/monospace,
    Montserrat / JetBrains Mono) in one translation unit, and every accessor
    (`hp_font_prop_data(i)`) indexes the array with a RUNTIME index.  The
    linker therefore has to keep the whole ~70 KB of glyph data even if the
    port only ever draws one size.
  * primeLua wants the 16 px proportional and monospace faces and nothing else:
    10.3 KB instead of 70 KB in the image, and primetcc itself is not touched.

So this script copies the two `hp_glyph` tables and their two bitmap pools
verbatim (renamed), and re-derives the two `hp_font` descriptors from the
original table literals.  Run it after a primetcc font update:

    python3 tools/make_font16.py            # writes port/plua_font16_data.c

The output is committed, so a normal build needs neither primetcc's
hp_fonts_data.c nor python: the file is self-contained.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOP = os.path.dirname(HERE)
PRIMETCC = os.environ.get(
    'PRIMETCC', os.path.join(os.path.dirname(TOP), 'primetcc'))
SRC = os.path.join(PRIMETCC, 'rt', 'hp_fonts_data.c')
OUT = os.path.join(TOP, 'port', 'plua_font16_data.c')

FACES = [('prop', 16), ('mono', 16)]


def array_text(src, name):
    """The whole `static const <type> name[...] = { ... };` declaration."""
    m = re.search(r'^static const [a-z_ ]*%s\[[^\]]*\] = \{.*?^\};' % re.escape(name),
                  src, re.S | re.M)
    if not m:
        raise SystemExit('array %s not found in %s' % (name, SRC))
    return m.group(0)


def table_entry(src, table, want_size):
    """The {size, line_h, ascent, first, last, glyphs, bits} row for a size."""
    m = re.search(r'static const hp_font %s\[4\] = \{(.*?)\n\};' % table,
                  src, re.S)
    if not m:
        raise SystemExit('table %s not found' % table)
    for row in re.findall(r'\{([^{}]*)\}', m.group(1)):
        fields = [f.strip() for f in row.split(',')]
        if len(fields) >= 7 and fields[0] == str(want_size):
            return fields
    raise SystemExit('no %d px row in %s' % (want_size, table))


def main():
    with open(SRC, encoding='utf-8') as fh:
        src = fh.read()

    chunks = []
    descs = []
    for face, size in FACES:
        glyphs = 'hp_glyphs_%s_%d' % (face, size)
        bits = 'hp_bits_%s_%d' % (face, size)
        fields = table_entry(src, 'hp_font_%s_table' % face, size)
        # hp_glyphs_prop_16 -> plua_glyphs_prop_16
        gtxt = array_text(src, glyphs).replace(glyphs, 'plua_' + glyphs[3:], 1)
        btxt = array_text(src, bits).replace(bits, 'plua_' + bits[3:], 1)
        chunks.append(gtxt)
        chunks.append(btxt)
        descs.append(
            'const hp_font plua_font_%s%d = {%s, %s, %s, %s, %s,\n'
            '                              plua_%s, plua_%s};'
            % (face, size, fields[0], fields[1], fields[2], fields[3],
               fields[4], glyphs[3:], bits[3:]))

    header = '''/*
 * plua_font16_data.c -- the two 16 px faces primeLua draws with.
 *
 * GENERATED by tools/make_font16.py from primetcc's rt/hp_fonts_data.c --
 * do not edit by hand.  The glyph descriptors and the packed 4-bit-per-pixel
 * bitmaps are copied verbatim (only renamed); the two hp_font rows are
 * re-derived from the original hp_font_prop_table / hp_font_mono_table.
 *
 * Fonts: Montserrat (proportional) and JetBrains Mono (monospace), both
 * SIL Open Font License 1.1, rendered offline by primetcc's fontgen2.py.
 * primetcc itself is not modified or linked: this file is self-contained.
 *
 * Cost in the image: 760 B glyphs + (2.9 KB | 4.7 KB) bitmaps per face, so
 * ~10.3 KB for both -- against ~70 KB for the full eight-face table, which is
 * what linking hp_fonts_data.c would pull in (its accessor indexes the table
 * with a runtime index, so --gc-sections cannot drop the other six faces).
 */
#include "hp_fonts.h"          /* the hp_glyph / hp_font layouts */

'''
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(header)
        fh.write('\n'.join(chunks))
        fh.write('\n\n/* the faces the port exposes (see the accessors below) */\n')
        fh.write('\n'.join(descs))
        fh.write('''

/*
 * primetcc's font engine (rt/hp_fonts.c, linked into the image unchanged) asks
 * for a face by index 0..3 via these two functions, expecting a valid font for
 * every index (hp_font_prop(16) picks the nearest size without a NULL check).
 * Only the 16 px faces exist here, so every index resolves to them: the engine
 * keeps working, and scripts get one size instead of four.
 */
const hp_font *hp_font_prop_data(int i)
{
\t(void)i;
\treturn &plua_font_prop16;
}

const hp_font *hp_font_mono_data(int i)
{
\t(void)i;
\treturn &plua_font_mono16;
}
''')

    size = os.path.getsize(OUT)
    print('%s: %d B written (2 faces, 16 px)' % (OUT, size))


if __name__ == '__main__':
    sys.exit(main())
