#!/usr/bin/env python3
"""make_font16_cascadia.py -- extract a THIRD 16 px face: Cascadia Code Light.

Why this exists: primeLua shipped two faces (port/plua_font16_data.c), Montserrat
(proportional) and JetBrains Mono, both copied out of primetcc's generated tables.
primetcc's own monospace face used to be Cascadia Code Light -- the comments in
rt/hp_fonts.h still say so -- and `examples/clock.lua` wants exactly that: a
fixed-cell face, where every glyph including ":" is the same width, so the big
clock digits never move.  Cascadia is not in primetcc's committed data any more
(its mono table holds JetBrains Mono now), so it is rasterized here instead:

    primetcc/rt/tools/fontgen2.py  (PIL, 4-bit alpha, same conventions)
        + fonts/Montserrat-w450.ttf, Montserrat-Regular.ttf,
          CascadiaCode-Light.ttf            ->  a full 8-face table in a temp file
        -> the mono 16 px rows are lifted out of THAT file and renamed.

primetcc is not modified: fontgen2.py is run read-only and its output is thrown
away after the extraction.  Run it after a primetcc font update:

    python3 tools/make_font16_cascadia.py        # writes port/plua_font16_cascadia_data.c

The output is committed, so a normal build needs neither PIL nor the TTF.
"""
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
TOP = os.path.dirname(HERE)
PRIMETCC = os.environ.get(
    'PRIMETCC', os.path.join(os.path.dirname(TOP), 'primetcc'))
GEN = os.path.join(PRIMETCC, 'rt', 'tools', 'fontgen2.py')
FONTS = os.path.join(PRIMETCC, 'rt', 'tools', 'fonts')
OUT = os.path.join(TOP, 'port', 'plua_font16_cascadia_data.c')

SIZE = 16
# fontgen2.py's argv: prop-12 (Montserrat Medium/w450), prop-16+ (Regular),
# mono (Cascadia Code Light) -- the files primetcc's own README documents
ARGV = ['Montserrat-w450.ttf', 'Montserrat-Regular.ttf', 'CascadiaCode-Light.ttf']


def array_text(src, name):
    m = re.search(r'^static const [a-z_ ]*%s\[[^\]]*\] = \{.*?^\};'
                  % re.escape(name), src, re.S | re.M)
    if not m:
        raise SystemExit('array %s not found in the generated table' % name)
    return m.group(0)


def table_entry(src, table, want_size):
    m = re.search(r'static const hp_font %s\[4\] = \{(.*?)\n\};' % table,
                  src, re.S)
    if not m:
        raise SystemExit('table %s not found' % table)
    for row in re.findall(r'\{([^{}]*)\}', m.group(1)):
        fields = [f.strip() for f in row.split(',')]
        if len(fields) >= 7 and fields[0] == str(want_size):
            return fields
    raise SystemExit('no %d px row in %s' % (want_size, table))


def generate():
    """fontgen2.py's output for all eight faces, in memory."""
    for name in ARGV:
        p = os.path.join(FONTS, name)
        if not os.path.exists(p):
            raise SystemExit('missing TTF: %s' % p)
    r = subprocess.run([sys.executable, GEN] + [os.path.join(FONTS, a)
                                               for a in ARGV],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit('fontgen2.py failed:\n' + r.stderr[-2000:])
    return r.stdout


def main():
    src = generate()
    fields = table_entry(src, 'hp_font_mono_table', SIZE)
    gtxt = array_text(src, 'hp_glyphs_mono_%d' % SIZE) \
        .replace('hp_glyphs_mono_%d' % SIZE, 'plua_glyphs_cascadia_%d' % SIZE, 1)
    btxt = array_text(src, 'hp_bits_mono_%d' % SIZE) \
        .replace('hp_bits_mono_%d' % SIZE, 'plua_bits_cascadia_%d' % SIZE, 1)

    header = '''/*
 * plua_font16_cascadia_data.c -- the Cascadia Code Light 16 px face.
 *
 * GENERATED by tools/make_font16_cascadia.py -- do not edit by hand.  The
 * glyph descriptors and the packed 4-bit-per-pixel bitmaps come from primetcc's
 * rt/tools/fontgen2.py run over rt/tools/fonts/CascadiaCode-Light.ttf (SIL
 * Open Font License 1.1); the hp_font row is re-derived from that run's
 * hp_font_mono_table.  primetcc is neither modified nor linked.
 *
 * Why a third face: the image's monospace face is JetBrains Mono, whose cell is
 * wider, and examples/clock.lua wants a face where EVERY glyph -- ":" included
 * -- has the same advance, so the big digits of a clock never shift.  Cascadia
 * Code Light is what primetcc itself used for its monospace family.
 *
 * Cost: ~%d B of glyphs+bitmaps in the image.
 */
#include "hp_fonts.h"          /* the hp_glyph / hp_font layouts */

''' % (len(gtxt) + len(btxt))

    desc = ('const hp_font plua_font_cascadia%d = {%s, %s, %s, %s, %s,\n'
            '                               plua_glyphs_cascadia_%d,'
            ' plua_bits_cascadia_%d};\n\n'
            '/* plua_hp.c\'s font.cascadia() asks for it by index; only this one\n'
            ' * size exists, so every index resolves to the same face. */\n'
            'const hp_font *plua_font_cascadia(int i)\n{\n\t(void)i;\n'
            '\treturn &plua_font_cascadia%d;\n}\n'
            % (SIZE, fields[0], fields[1], fields[2], fields[3], fields[4],
               SIZE, SIZE, SIZE))

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(header)
        fh.write(gtxt)
        fh.write('\n\n')
        fh.write(btxt)
        fh.write('\n\n')
        fh.write(desc)

    print('%s: %d B written (Cascadia Code Light %d px, cell %s px)'
          % (OUT, os.path.getsize(OUT), SIZE, fields[4]))


if __name__ == '__main__':
    sys.exit(main())
