#!/usr/bin/env python3
"""make_font_big.py -- a NATIVE big digit face for the clock demo.

primeLua ships two text families at 16 / 24 / 32 px (Montserrat proportional,
Cascadia Code Light monospace -- tools/make_font_montserrat.py and
tools/make_font_cascadia.py).  A wall clock wants more than that: at 32 px the
digits are 152 px of a 320 px screen wide and 38 px tall, which reads as a
status line, not as a clock.

WHY NOT JUST SCALE THE 32 px FACE: magnifying an antialiased bitmap magnifies
its soft edges too.  Every 1 px coverage fringe becomes a 2 px grey band, and
the digits look blurry on the calculator -- which is exactly what the first
version of the demo did (it rendered into a GROB and blitted the pixels back
scaled, and it looked it).

The fix is to rasterize the face AT THE SIZE IT IS DRAWN.  Cascadia Code Light
is a vector font, so 56 px is rendered with proper 56 px coverage -- and the
face only has to carry the glyphs a clock uses, so it is small:

    glyphs 0x2D..0x3A ('-' '.' '/' 0-9 ':'), 4-bit alpha, 14 glyphs

At 56 px that is ~6.6 KB, against ~40 KB for the full ASCII range at the same
size (and it takes the GROB + getpixel + blitpixels chain out of the demo).

Rendering goes through primetcc's rt/tools/fontgen2.py (imported, not copied),
so the quantisation, the nibble order, the row padding and the fixed-cell
centering are identical to the faces the engine already draws.  primetcc is not
modified.  Output is committed, so a normal build needs neither PIL nor the TTF.

    python3 tools/make_font_big.py            # 56 px (the default)
    python3 tools/make_font_big.py 64         # 8 cells = 304 px wide, the max
    make font-big BIGSIZE=64                  # same thing through make

Screen budget at 320 px: 8 cells of "HH:MM:SS" are 8 x round(0.586*size), i.e.
152 px at 32, 224 at 48, 264 at 56, 304 at 64.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOP = os.path.dirname(HERE)
PRIMETCC = os.environ.get(
    'PRIMETCC', os.path.join(os.path.dirname(TOP), 'primetcc'))
FONTGEN_DIR = os.path.join(PRIMETCC, 'rt', 'tools')
TTF = os.path.join(FONTGEN_DIR, 'fonts', 'CascadiaCode-Light.ttf')
OUT = os.path.join(TOP, 'port', 'plua_font_big_data.c')

FIRST, LAST = 0x2D, 0x3A          # '-', '.', '/', '0'..'9', ':'
DEFAULT_SIZE = 56


def main():
    size = int(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SIZE
    sys.path.insert(0, FONTGEN_DIR)
    try:
        import fontgen2
        from PIL import ImageFont
    except ImportError as e:
        raise SystemExit('needs primetcc/rt/tools/fontgen2.py and PIL: %s' % e)

    if not os.path.exists(TTF):
        raise SystemExit('missing TTF: %s' % TTF)
    f = ImageFont.truetype(TTF, size)
    ascent, descent = f.getmetrics()
    line_h = ascent + descent

    # render the subset, then center every glyph in one fixed cell (the same
    # rule fontgen2 uses for its monospace family)
    glyphs = []
    for ch in range(FIRST, LAST + 1):
        adv = max(1, int(round(f.getlength(chr(ch)))))
        glyphs.append(fontgen2.render_glyph(f, size, ch, adv))
    cell = max([g['adv'] for g in glyphs] + [g['w'] for g in glyphs])
    for g in glyphs:
        g['adv'] = cell
        if g['w']:
            g['xoff'] = (cell - g['w']) // 2

    pool = []
    gdefs = []
    for g in glyphs:
        off = len(pool)
        pool += fontgen2.pack_rows(g['rows'], g['w'])
        gdefs.append('    {%d, %d, %d, %d, %d, %d}'
                     % (g['w'], g['h'], g['xoff'], g['yoff'], g['adv'], off))

    name = 'big%d' % size
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('''/*
 * plua_font_big_data.c -- the NATIVE %d px digit face (Cascadia Code Light).
 *
 * GENERATED by tools/make_font_big.py -- do not edit by hand; run
 * `make font-big BIGSIZE=%d` to regenerate.  Rendered by primetcc's
 * rt/tools/fontgen2.py from rt/tools/fonts/CascadiaCode-Light.ttf (SIL Open
 * Font License 1.1), so the 4-bit coverage, nibble order and row padding match
 * every other face in the image.  primetcc is neither modified nor linked.
 *
 * Glyphs 0x%02X..0x%02X only ('-' '.' '/' '0'-'9' ':'): a clock needs nothing
 * else, and 14 glyphs are %d B instead of the ~%d KB a full ASCII range would
 * take at this size.  Characters outside the range draw NOTHING and advance 0
 * (hp_fonts.c skips them), so do not use this face for arbitrary text -- the
 * two text families at 16/24/32 px are what general text draws with.
 *
 * Why this exists: the clock's digits have to be big AND sharp.  Magnifying the
 * 32 px face (what the first version did) magnifies its antialiased edges into
 * wide grey fringes -- blurry on the calculator.  A face rasterized at the size
 * it is drawn has clean edges.
 */
#include "hp_fonts.h"

''' % (size, size, FIRST, LAST, len(pool),
            40 * (LAST - FIRST + 1) / 1024.0))
        fh.write('static const hp_glyph plua_glyphs_%s[%d] = {\n'
                 % (name, LAST - FIRST + 1))
        fh.write(',\n'.join(gdefs))
        fh.write('\n};\n')
        fh.write('static const unsigned char plua_bits_%s[%d] = {\n'
                 % (name, len(pool)))
        for i in range(0, len(pool), 16):
            fh.write('    ' + ', '.join('0x%02X' % b
                                        for b in pool[i:i + 16]) + ',\n')
        fh.write('};\n\n')
        fh.write('const hp_font plua_font_%s = {%d, %d, %d, 0x%02X, 0x%02X,\n'
                 '                            plua_glyphs_%s, plua_bits_%s};\n'
                 % (name, size, line_h, ascent, FIRST, LAST, name, name))
        fh.write('''
/* font.big() in plua_hp.c asks for it here; there is ONE big face, and changing
 * its size means regenerating this file (the accessor name does not change, so
 * clock.lua and friends never have to know which size it is). */
const hp_font *plua_font_big(void)
{
\treturn &plua_font_%s;
}
''' % name)

    print('%s: %d B written (%s: %d px face, cell %d px, %d glyphs, %d B bitmap)'
          % (OUT, os.path.getsize(OUT), name, size, cell,
             LAST - FIRST + 1, len(pool)))


if __name__ == '__main__':
    sys.exit(main())
